config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	devise_scope :user do
		authenticated :user do
			root 'dashboard#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end

	resources :users
	resources :dashboard do
		get 'super_admin',							on: :collection
		get 'organization_super_admin',				on: :collection
		get 'organization_dept_admin',				on: :collection
		get 'organization_editors',					on: :collection
		get 'organization_reviewers',				on: :collection
		get 'organization_students',				on: :collection
		get 'activate_organization',				on: :collection
		get 'reject_organization',					on: :collection
		get 'org_join_request',						on: :collection
		get 'approve_org_user',						on: :collection
		get 'reject_org_user',						on: :collection
		get 'dept_join_request',					on: :collection
		get 'approve_dept_user',					on: :collection
		get 'reject_dept_user',						on: :collection
		get 'forward_for_review',					on: :collection
		get 'reviewer_accepted',					on: :collection
		get 'reviewer_rejected',					on: :collection

	end
	resources :organizations
	resources :departments do
		get 'change_admin',							on: :collection
		patch 'update_admin',						on: :collection
	end

  	resources :user_posts do
  	end

  	resources :editor
	resources :reviewer

	if Rails.env.development?
		mount LetterOpenerWeb::Engine, at: "/letter_opener"
	end
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	
	before_action :super_admin_only!, only: [:super_admin, :activate_organization, :reject_organization]
	before_action :org_super_admin_only!, only: [:organization_super_admin, :approve_org_user, :reject_org_user]
	before_action :dept_admin_only!, only: [:organization_dept_admin]
	before_action :dept_editor_only!, only: [:organization_editors]
	before_action :dept_reviewer_only!, only: [:organization_reviewers]
	before_action :student_only!, only: [:organization_students]

	def index
		if current_user.superadmin?
			redirect_to super_admin_dashboard_index_path
		elsif current_user.org_super_admin?
			redirect_to organization_super_admin_dashboard_index_path
		elsif current_user.dept_admin?
			redirect_to organization_dept_admin_dashboard_index_path
		elsif current_user.dept_editor?
			redirect_to organization_editors_dashboard_index_path
		elsif current_user.dept_reviewer?
			redirect_to organization_reviewers_dashboard_index_path
		elsif current_user.student?
			redirect_to organization_students_dashboard_index_path
		end

		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")
		@currentUser = current_user.id
	end

	def super_admin
		@organizations = Organization.all.where(status: "inactive")
	end

	def organization_super_admin
		@departments = Department.all

		@currentUser = current_user
		@org_id = @currentUser.organization_id
		@requests = Request.all.where(org_id: @org_id)
	end

	def activate_organization
		@organization = Organization.find(params[:id])
		setStatus = Organization.statuses[:closed]
		@organization.status = setStatus

		@user = User.new
		@user.email = @organization.email
		@generated_password = Devise.friendly_token.first(10)
		@user.password = @generated_password
		@user.role = User.roles[:org_super_admin]
		@user.organization_id = @organization.id

		if User.exists?(@organization.email)
			flash[:alert] = "User exists. You have to change email address."
			render :super_admin
		else
			if @organization.save
				if @user.save
					OrgNotificationMailer.organization_created_notification(@organization.name, @user.email, @generated_password).deliver
				end
				flash[:success] = "Organization has been activated!"
				redirect_to dashboard_index_path
			else
				flash[:alert] = "Organization can not be activated."
				render :super_admin
			end
		end
		
	end

	def reject_organization
	end

	def org_join_request
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")
		@org_id = Organization.find(params[:id])
		@currentUser = current_user.id

		@request = Request.new
		@request.user_id = @currentUser
		@request.org_id = @org_id.id
		@request.status = Request.requests[:pending]
		@request.requested_at = Time.now

		if @request.save
			flash[:success] = "Request has been sent successfully."
			redirect_to dashboard_index_path
		else
			flash[:alert] = "An error occurred. Please try again."
			render :index
		end
	end

	def approve_org_user
		@request = Request.find(params[:id])
		@request.status = Request.requests[:accepted]

		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.organization_id = @request.org_id

		if @request.save and @requestee.save
			flash[:success] = "Approved user"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reject_org_user
		@request = Request.find(params[:id])
		@request.status = Request.requests[:rejected]

		if @request.save
			flash[:alert] = "User rejected"
			redirect_to dashboard_index_path
		end
	end

	def organization_dept_admin
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)

		@assing_candidates = User.all.where(organization_id: @cu_org_id).where(role: "user")
	end

	def dept_join_request
		@organization = Organization.find(params[:o_id])
		@dept_id = Department.find(params[:id])
		@currentUser = current_user.id

		@d_request = DeptRequest.new
		@d_request.user_id = @currentUser
		@d_request.department_id = @dept_id.id
		@d_request.status = DeptRequest.requests[:pending]
		@d_request.requests = Time.now

		if @d_request.save!
			flash[:success] = "Request has been sent successfully."
			redirect_to organization_path(@organization)
		else
			flash[:alert] = "An error occurred. Please try again."
			redirect_to organization_path(@organization)
		end
	end

	def approve_dept_user
		@request = DeptRequest.find(params[:id])
		@request.status = DeptRequest.requests[:accepted]

		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.department_id = @request.department_id
		@requestee.role = User.roles[:student]

		if @request.save and @requestee.save
			flash[:success] = "Approved user"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reject_dept_user
		@request = DeptRequest.find(params[:id])
		@request.status = DeptRequest.requests[:rejected]
		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.role = User.roles[:user]

		if @request.save
			flash[:alert] = "User rejected"
			redirect_to dashboard_index_path
		end
	end

	def organization_editors
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)
		@post_requests = UserPost.all.where(privacy: UserPost.privacies[:private_post])
	end

	def forward_for_review
		@post = UserPost.find(params[:id])
		@post.edit_status = UserPost.edit_statuses[:forwarded]

		if @post.save
			flash[:success] = "Forwarded successfully"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def organization_reviewers
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)
		@review_posts = UserPost.all.where(edit_status: UserPost.edit_statuses[:forwarded])

		@review = Reviewer.new
	end

	def reviewer_accepted
		@post = UserPost.find(params[:id])
		@post.review_status = UserPost.review_statuses[:on_review]

		if @post.save
			flash[:success] = "Accepted"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reviewer_rejected
		@post = UserPost.find(params[:id])
		@post.review_status = UserPost.review_statuses[:rejected]

		if @post.save
			flash[:success] = "Accepted"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def organization_students
		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<section id="dashboard-home">
	<div class="row">
		<div class="col-sm-12 request-org">
			<%= link_to "CREATE AN ORGANIZATION", new_organization_path, :class => "btn btn-primary" %>
		</div><br><br>
	</div>
	<hr>
	<div class="row">
		<div class="col-sm-12">

			<% @organizations.each do |organization| %>
			<div class="col-sm-3 org-box">
				<div class="org-box-wrapper">
					<div class="title"><a href=""><%= organization.name %></a></div>
					<div class="info">
						<ul>
							<li class="members"><%= User.all.where(organization_id: organization.id).count > 0 ? User.all.where(organization_id: organization.id).count : 0 %> members</li>
							<li></li>
							<% if User.find(@currentUser).requests.where(org_id: organization.id).where(status: 0).exists? %>
								<li>
									<button class="btn btn-warning">Pending</button>
								</li>
							<% elsif User.find(@currentUser).requests.where(org_id: organization.id).where(status: 1).exists? %>
								<li><%= link_to "Enter", organization_path(organization.id), :class=>"btn btn-primary" %></li>
								<li>
									<button class="btn btn-success">Member</button>
								</li>
							<% else %>
								<li>
									<%= link_to "Request to join", org_join_request_dashboard_index_path(:id => organization.id), :class => "btn btn-info" %>
								</li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</section><!--#dashboard-home-->

app/views/dashboard/organization_dept_admin.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Overview</a></li>
	<li role="presentation"><a href="#request" aria-controls="request" role="tab" data-toggle="tab">Requests</a></li>
	<li role="presentation"><a href="#assign_role" aria-controls="assign_role" role="tab" data-toggle="tab">Assign Role</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">
	<%= render :partial => "dashboard/partials/dashboard" %>
</div>
<div role="tabpanel" class="tab-pane" id="request">
	<table class="table table-striped">
		<thead>
			<th>Organization</th>
			<th>Requested from</th>
			<th>Status</th>
			<th></th>
		</thead>
		<tbody>
			<% @requests.each do |request| %>
			<tr>
				<td><%= request.department.nil? ? "": request.department.name %></td>
				<td><%= request.user.email %></td>
				<td>
					<% if request.status == 0 %>
						Pending
					<% elsif request.status == 2 %>
						Rejected
					<% else %>
						Approved
					<% end %>
				</td>
				<td>
					<% if request.status == 0 %>
						<%= link_to "Approve", approve_dept_user_dashboard_index_path(:id => request.id) %>
						&nbsp;&#8226;&nbsp;
						<%= link_to "Reject", reject_dept_user_dashboard_index_path(:id => request.id) %>
					<% elsif request.status == 2 %>
						<%= link_to "Approve", approve_dept_user_dashboard_index_path(:id => request.id) %>
					<% else %>
						<%= link_to "Reject", reject_dept_user_dashboard_index_path(:id => request.id) %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div role="tabpanel" class="tab-pane" id="assign_role">
<table class="table table-striped">
		<thead>
			<th>User</th>
			<th>Select</th>
			<th></th>
		</thead>
		<tbody>
			<% @assing_candidates.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td>
					<%= bootstrap_form_for user, url: user_path(user), multipart: true, remote: true, layout: :vertical do |f| %>
						<%= f.hidden_field :id, value: user.id%>
						<%= f.hidden_field :department_id, value: @dept_id%>
						<%= f.select :role, User.roles.keys.reject { |s| s == "superadmin" or s == "org_super_admin" or s == "dept_admin" }.map { |w| [w.humanize, w] }%>
						<%= f.submit "Assign Role", :class => 'btn btn-primary'%>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>

app/views/dashboard/organization_editors.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
	<li role="presentation"><a href="#my_org" aria-controls="my_org" role="tab" data-toggle="tab">My Organization</a></li>
	<li role="presentation"><a href="#edit_rqst" aria-controls="edit_rqst" role="tab" data-toggle="tab">Edit request</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">My Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">
	<%= render :partial => "dashboard/partials/dashboard" %>
</div>
<div role="tabpanel" class="tab-pane" id="my_org">
	<%= render :partial => "dashboard/partials/organization" %>
</div>
<div role="tabpanel" class="tab-pane" id="edit_rqst">
	<table class="table table-striped">
		<thead>
			<th>Requested from</th>
			<th>Post type</th>
			<th>Current status</th>
			<th>Document?</th>
			<th></th>
		</thead>
		<tbody>
			<% @post_requests.each do |post| %>
			<tr>
				<td><%= User.find(post.user_id).email %></td>
				<td><%= post.post_type %></td>
				<td>
					<strong>Editor:</strong> <%= post.edit_status.humanize %> <br>
					<strong>Reviewer:</strong> <%= post.review_status.humanize %>
				</td>
				<td><%= post.document.exists? ? "YES" : "NO" %></td>
				<td> <%= link_to "Forward", forward_for_review_dashboard_index_path(:id => post.id) %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>

app/views/dashboard/organization_reviewers.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
	<li role="presentation"><a href="#my_org" aria-controls="my_org" role="tab" data-toggle="tab">My Organization</a></li>
	<li role="presentation"><a href="#edit_rqst" aria-controls="edit_rqst" role="tab" data-toggle="tab">Forwarded request</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">My Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">
	<%= render :partial => "dashboard/partials/dashboard" %>
</div>
<div role="tabpanel" class="tab-pane" id="my_org">
	<%= render :partial => "dashboard/partials/organization" %>
</div>
<div role="tabpanel" class="tab-pane" id="edit_rqst">
	<table class="table table-striped reviewer-table">
		<thead>
			<th>Requested from</th>
			<th>Post type</th>
			<th>Current status</th>
			<th>Document?</th>
			<th></th>
		</thead>
		<tbody>
			<% @review_posts.each do |post| %>
			<tr>
				<td><%= User.find(post.user_id).email %></td>
				<td><%= post.post_type %></td>
				<td>
					<strong>Editor:</strong> <%= post.edit_status.humanize %> <br>
					<strong>Reviewer:</strong> <%= post.review_status.humanize %>
				</td>
				<td><%= post.document.exists? ? "<a href='post.document.url'>Download</a>" : "NO" %></td>
				<td> 
					<%= bootstrap_form_for @review, url: reviewer_index_path, multipart: true, html: {class: "feedback", id: "feedback"}, remote: true, layout: :vertical do |f| %>
						<%= f.hidden_field :post_id, value: post.id%>
						<%= f.text_area :feedback, :placeholder => "Write feedback here", :rows => '3', :cols => '100' %>
						<%= f.submit "Post", :class => 'btn btn-info'%>
					<% end %>
					<a id="show-feedback" class="btn btn-info review-control">Feedback</a>
					<%= link_to "Reject", reviewer_rejected_dashboard_index_path(:id => post.id), :class => "btn btn-danger review-control" %>
					<%= link_to "Accept", reviewer_accepted_dashboard_index_path(:id => post.id), :class => "btn btn-success review-control" %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>

app/views/dashboard/organization_students.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Dashboard</a></li>
	<li role="presentation"><a href="#my_org" aria-controls="my_org" role="tab" data-toggle="tab">My Organization</a></li>
	<li role="presentation"><a href="#my_posts" aria-controls="my_posts" role="tab" data-toggle="tab">My Posts</a></li>
	<li role="presentation"><a href="#all_org" aria-controls="all_org" role="tab" data-toggle="tab">All Organizations</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">My Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">
	<%= render :partial => "dashboard/partials/dashboard" %>
</div>
<div role="tabpanel" class="tab-pane" id="my_org">
	<%= render :partial => "dashboard/partials/organization" %>
</div>
<div role="tabpanel" class="tab-pane" id="my_posts">
	<table class="table table-striped reviewer-table">
		<thead>
			<th>Post type</th>
			<th>Content</th>
			<th>Document?</th>
			<th>Editor status</th>
			<th>Reviewer status</th>
			<th>Feedback?</th>
			<th></th>
		</thead>
		<tbody>
			<% @reviewed_post.each do |post| %>
				<tr>
					<td><%= post.post_type %></td>
					<td><%= post.post_content %></td>
					<td>
						<% if post.document.exists? %> 
							<a href='<%=post.document.url%>'>Download</a> 
						<% elsif %> 
							NO 
						<% end %>
					</td>
					<td><strong>Editor:</strong> <%= post.edit_status.humanize %></td>
					<td><strong>Reviewer:</strong> <%= post.review_status.humanize %></td>
					<td>
						<ul>
							<% @reviews.each do |reviews| %>
								<%if reviews.post_id == post.id%>
									<li><%= reviews.feedback %></li>
								<%end%>
							<% end %>
						</ul>
					</td>
					<td></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div role="tabpanel" class="tab-pane" id="all_org">
	<%= render :partial => "dashboard/partials/organization_all" %>
</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>

app/views/dashboard/organization_super_admin.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Overview</a></li>
	<li role="presentation"><a href="#request" aria-controls="request" role="tab" data-toggle="tab">Join Requests</a></li>
	<li role="presentation"><a href="#activity" aria-controls="activity" role="tab" data-toggle="tab">Activity</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">
	<br>
	<div class="row">

	<div class="col-sm-6">
		<div class="request-org">
			<%= link_to "CREATE A DEPARTMENT", new_department_path, :class => "btn btn-primary" %>
		</div>
	</div>
	<div class="col-sm-6 dept-box">
		<h3><strong>ALL DEPARTMENTS</strong></h3>
		<div class="dept-box-wrapper">
			<% @departments.each do |department| %>
				<div class="row dept-row">
					<div class="col-sm-1 dept-icon"> 
						<!--<%if department.image.present?%>
							<%= image_tag "#{department.image}" %>
						<%end%>
						-->
						<img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png">
					</div>
					<div class="col-sm-6 text-left"> <%= link_to department.name, edit_department_path(department)%> </div>
					<div class="col-sm-5"> 
						<%= link_to "Edit", edit_department_path(department)%>
						&nbsp;&#8226;&nbsp;
						<%= link_to "Change admin", change_admin_departments_path(:id => department.id)%>
						&nbsp;&#8226;&nbsp;
						<%= link_to "Delete", department_path(department), method: :delete, data: {confirm: "Are you sure?"}%>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	</div>
</div>
<div role="tabpanel" class="tab-pane" id="request">
	<table class="table table-striped">
		<thead>
			<th>Organization</th>
			<th>Requested from</th>
			<th>Status</th>
			<th></th>
		</thead>
		<tbody>
			<% @requests.each do |request| %>
			<tr>
				<td><%= request.organization.nil? ? "": request.organization.name %></td>
				<td><%= request.user.email %></td>
				<td>
					<% if request.status == 0 %>
						Pending
					<% elsif request.status == 2 %>
						Rejected
					<% else %>
						Approved
					<% end %>
				</td>
				<td>
					<% if request.status == 0 %>
						<%= link_to "Approve", approve_org_user_dashboard_index_path(:id => request.id) %>
						&nbsp;&#8226;&nbsp;
						<%= link_to "Reject", reject_org_user_dashboard_index_path(:id => request.id) %>
					<% elsif request.status == 2 %>
						<%= link_to "Approve", approve_org_user_dashboard_index_path(:id => request.id) %>
					<% else %>
						<%= link_to "Reject", reject_org_user_dashboard_index_path(:id => request.id) %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	
</div>
<div role="tabpanel" class="tab-pane" id="activity">...</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>

app/views/dashboard/super_admin.html.erb
 <!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Overview</a></li>
	<li role="presentation"><a href="#request" aria-controls="request" role="tab" data-toggle="tab">Requests</a></li>
	<li role="presentation"><a href="#activity" aria-controls="activity" role="tab" data-toggle="tab">Activity</a></li>
	<li role="presentation"><a href="#account" aria-controls="account" role="tab" data-toggle="tab">Account</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
<div role="tabpanel" class="tab-pane active" id="home">...</div>
<div role="tabpanel" class="tab-pane" id="request">
	<table class="table table-striped">
		<thead>
			<th>Name</th>
			<th>Email</th>
			<th></th>
		</thead>
		<tbody>
			<% @organizations.each do |organization| %>
			<tr>
				<td><%= organization.name %></td>
				<td><%= organization.email %></td>
				<td>
					<%= link_to "Activate", activate_organization_dashboard_index_path(:id => organization.id) %>
					&nbsp;&#8226;&nbsp;
					<%= link_to "Reject", reject_organization_dashboard_index_path(:id => organization.id) %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	
</div>
<div role="tabpanel" class="tab-pane" id="activity">...</div>
<div role="tabpanel" class="tab-pane" id="account">...</div>
</div>