config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	devise_scope :user do
		authenticated :user do
			root 'dashboard#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end

	resources :users
	resources :dashboard do
		get 'super_admin',							on: :collection
		get 'organization_super_admin',				on: :collection
		get 'organization_dept_admin',				on: :collection
		get 'organization_editors',					on: :collection
		get 'organization_reviewers',				on: :collection
		get 'organization_students',				on: :collection
		get 'activate_organization',				on: :collection
		get 'reject_organization',					on: :collection
		get 'org_join_request',						on: :collection
		get 'approve_org_user',						on: :collection
		get 'reject_org_user',						on: :collection
		get 'dept_join_request',					on: :collection
		get 'approve_dept_user',					on: :collection
		get 'reject_dept_user',						on: :collection
		get 'forward_for_review',					on: :collection
		get 'reviewer_accepted',					on: :collection
		get 'reviewer_rejected',					on: :collection

	end
	resources :organizations
	resources :departments do
		get 'change_admin',							on: :collection
		patch 'update_admin',						on: :collection
	end

  	resources :user_posts do
  	end

  	resources :editor
	resources :reviewer

	if Rails.env.development?
		mount LetterOpenerWeb::Engine, at: "/letter_opener"
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_one :posts
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	has_many :dept_requests
end

app/models/dept_request.rb
class DeptRequest < ApplicationRecord

	enum request: [:pending, :accepted, :rejected]
	after_initialize :set_default_request, :if => :new_record?

	def set_default_request
		self.status ||= :pending
	end

	validates_uniqueness_of :user_id, scope: [:department_id]

	belongs_to :user
	belongs_to :department, optional: true
end

app/models/editor.rb
class Editor < ApplicationRecord
	has_many :posts
end

app/models/organization.rb
class Organization < ApplicationRecord
	enum status: [:open, :secret, :closed, :inactive]
	after_initialize :set_default_status, :if => :new_record?

	def set_default_status
		self.status ||= :inactive
	end

	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :requests,    class_name: "Request", foreign_key: "org_id"
	has_many :users
end

app/models/request.rb
class Request < ApplicationRecord

	enum request: [:pending, :accepted, :rejected]
	after_initialize :set_default_request, :if => :new_record?

	def set_default_request
		self.status ||= :pending
	end

	validates_uniqueness_of :user_id, scope: [:org_id]

	belongs_to :user
	belongs_to :organization,    class_name: "Organization", foreign_key: "org_id", optional: true
end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
	belongs_to :user_post,    class_name: "UserPost", foreign_key: "id", optional: true
end

app/models/user.rb
class User < ApplicationRecord

	enum role: [:superadmin, :user, :org_super_admin, :dept_admin, :dept_editor, :dept_reviewer, :student]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	has_many :requests
	has_many :dept_requests
	has_many :user_posts

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable
end

app/models/user_post.rb
class UserPost < ApplicationRecord

	has_attached_file :document, :path => ":rails_root/public/system/:attachment/:id/:style/:filename"

	allowed_content_type = [
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/jpg',
    'image/gif'
    ]
	validates_attachment_content_type :document, :content_type => allowed_content_type, :message=> "Only #{allowed_content_type} is allowed"

	enum post_type: [:file, :post, :both]
	enum privacy: [:public_post, :private_post]
	enum genre: [:post_only, :article, :paper, :concept]
	enum edit_status: [:pending, :forwarded, :accepted]
	enum review_status: [:no_reviewer, :on_review, :rejected, :complete]

	after_initialize :set_default_privacy, :if => :new_record?
	after_initialize :set_default_edit_status, :if => :new_record?
	after_initialize :set_default_review_status, :if => :new_record?

	def set_default_privacy
		self.privacy ||= :private_post
	end

	def set_default_edit_status
		self.edit_status ||= :pending
	end

	def set_default_review_status
		self.review_status ||= :no_reviewer
	end

	has_many :comments
	has_one :users
	has_one :editors
	has_many :reviewers,    class_name: "Reviewer", foreign_key: "post_id"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!, :only => [:index]

	def index
	end
end

app/controllers/user_posts_controller.rb
class UserPostsController < ApplicationController

  def create
    @currentUser = current_user
    @user_post = UserPost.new(user_post_params)
    @user_post.user_id = current_user.id
    @user_post.department_id = current_user.department_id
    
    if @user_post.save
      flash[:success] = "Posted successfully."
      redirect_to dashboard_index_path
    else
      flash[:error] = "An error occurred. Please try again."
      redirect_to dashboard_index_path
    end
  end

  def update
    if @user_post.update
      flash[:success] = "Updated successfully."
      redirect_to dashboard_index_path
    else
      flash[:error] = "An error occurred. Please try again."
      redirect_to dashboard_index_path
    end
  end

  def destroy
    @user_post = UserPost.find(params[:id])
    @user_post.destroy

    flash[:success] = "Post deleted successfully."
    redirect_to dashboard_index_path
  end

  private

    def user_post_params
      params.require(:user_post).permit(:user_id, :document, :department_id, :post_type, :post_content, :privacy, :post_genre, :edit_status, :review_status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	after_action :verify_authorized

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])

		if user.update_attributes(secure_params)
			redirect_to users_path, :notice => "User updated."
	    else
	      redirect_to users_path, :alert => "Unable to update user."
	    end
	end

	def destroy
		user = User.find(params[:id])

		user.destroy
		redirect_to users_path, :notice => "User deleted"
	end

	private

	def secure_params
		params.require(:user).permit(:id, :role, :department_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/reviewer_helper.rb
module ReviewerHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_posts/_form.html.erb
<%= form_with(model: user_post, local: true) do |form| %>
  <% if user_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_post.errors.count, "error") %> prohibited this user_post from being saved:</h2>

      <ul>
      <% user_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :user_post_user_id %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.number_field :department_id, id: :user_post_department_id %>
  </div>

  <div class="field">
    <%= form.label :post_type %>
    <%= form.number_field :post_type, id: :user_post_post_type %>
  </div>

  <div class="field">
    <%= form.label :post_content %>
    <%= form.text_area :post_content, id: :user_post_post_content %>
  </div>

  <div class="field">
    <%= form.label :privacy %>
    <%= form.number_field :privacy, id: :user_post_privacy %>
  </div>

  <div class="field">
    <%= form.label :post_genre %>
    <%= form.number_field :post_genre, id: :user_post_post_genre %>
  </div>

  <div class="field">
    <%= form.label :edit_status %>
    <%= form.number_field :edit_status, id: :user_post_edit_status %>
  </div>

  <div class="field">
    <%= form.label :review_status %>
    <%= form.number_field :review_status, id: :user_post_review_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_posts/edit.html.erb
<h1>Editing User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Show', @user_post %> |
<%= link_to 'Back', user_posts_path %>

app/views/user_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Department</th>
      <th>Post type</th>
      <th>Post content</th>
      <th>Privacy</th>
      <th>Post genre</th>
      <th>Edit status</th>
      <th>Review status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_posts.each do |user_post| %>
      <tr>
        <td><%= user_post.user_id %></td>
        <td><%= user_post.department_id %></td>
        <td><%= user_post.post_type %></td>
        <td><%= user_post.post_content %></td>
        <td><%= user_post.privacy %></td>
        <td><%= user_post.post_genre %></td>
        <td><%= user_post.edit_status %></td>
        <td><%= user_post.review_status %></td>
        <td><%= link_to 'Show', user_post %></td>
        <td><%= link_to 'Edit', edit_user_post_path(user_post) %></td>
        <td><%= link_to 'Destroy', user_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Post', new_user_post_path %>

app/views/user_posts/new.html.erb
<h1>New User Post</h1>

<%= render 'form', user_post: @user_post %>

<%= link_to 'Back', user_posts_path %>

app/views/user_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_post.user_id %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user_post.department_id %>
</p>

<p>
  <strong>Post type:</strong>
  <%= @user_post.post_type %>
</p>

<p>
  <strong>Post content:</strong>
  <%= @user_post.post_content %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @user_post.privacy %>
</p>

<p>
  <strong>Post genre:</strong>
  <%= @user_post.post_genre %>
</p>

<p>
  <strong>Edit status:</strong>
  <%= @user_post.edit_status %>
</p>

<p>
  <strong>Review status:</strong>
  <%= @user_post.review_status %>
</p>

<%= link_to 'Edit', edit_user_post_path(@user_post) %> |
<%= link_to 'Back', user_posts_path %>