config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	devise_scope :user do
		authenticated :user do
			root 'dashboard#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end

	resources :users
	resources :dashboard do
		get 'super_admin',							on: :collection
		get 'organization_super_admin',				on: :collection
		get 'organization_dept_admin',				on: :collection
		get 'organization_editors',					on: :collection
		get 'organization_reviewers',				on: :collection
		get 'organization_students',				on: :collection
		get 'activate_organization',				on: :collection
		get 'reject_organization',					on: :collection
		get 'org_join_request',						on: :collection
		get 'approve_org_user',						on: :collection
		get 'reject_org_user',						on: :collection
		get 'dept_join_request',					on: :collection
		get 'approve_dept_user',					on: :collection
		get 'reject_dept_user',						on: :collection
		get 'forward_for_review',					on: :collection
		get 'reviewer_accepted',					on: :collection
		get 'reviewer_rejected',					on: :collection

	end
	resources :organizations
	resources :departments do
		get 'change_admin',							on: :collection
		patch 'update_admin',						on: :collection
	end

  	resources :user_posts do
  	end

  	resources :editor
	resources :reviewer

	if Rails.env.development?
		mount LetterOpenerWeb::Engine, at: "/letter_opener"
	end
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	
	before_action :super_admin_only!, only: [:super_admin, :activate_organization, :reject_organization]
	before_action :org_super_admin_only!, only: [:organization_super_admin, :approve_org_user, :reject_org_user]
	before_action :dept_admin_only!, only: [:organization_dept_admin]
	before_action :dept_editor_only!, only: [:organization_editors]
	before_action :dept_reviewer_only!, only: [:organization_reviewers]
	before_action :student_only!, only: [:organization_students]

	def index
		if current_user.superadmin?
			redirect_to super_admin_dashboard_index_path
		elsif current_user.org_super_admin?
			redirect_to organization_super_admin_dashboard_index_path
		elsif current_user.dept_admin?
			redirect_to organization_dept_admin_dashboard_index_path
		elsif current_user.dept_editor?
			redirect_to organization_editors_dashboard_index_path
		elsif current_user.dept_reviewer?
			redirect_to organization_reviewers_dashboard_index_path
		elsif current_user.student?
			redirect_to organization_students_dashboard_index_path
		end

		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")
		@currentUser = current_user.id
	end

	def super_admin
		@organizations = Organization.all.where(status: "inactive")
	end

	def organization_super_admin
		@departments = Department.all

		@currentUser = current_user
		@org_id = @currentUser.organization_id
		@requests = Request.all.where(org_id: @org_id)
	end

	def activate_organization
		@organization = Organization.find(params[:id])
		setStatus = Organization.statuses[:closed]
		@organization.status = setStatus

		@user = User.new
		@user.email = @organization.email
		@generated_password = Devise.friendly_token.first(10)
		@user.password = @generated_password
		@user.role = User.roles[:org_super_admin]
		@user.organization_id = @organization.id

		if User.exists?(@organization.email)
			flash[:alert] = "User exists. You have to change email address."
			render :super_admin
		else
			if @organization.save
				if @user.save
					OrgNotificationMailer.organization_created_notification(@organization.name, @user.email, @generated_password).deliver
				end
				flash[:success] = "Organization has been activated!"
				redirect_to dashboard_index_path
			else
				flash[:alert] = "Organization can not be activated."
				render :super_admin
			end
		end
		
	end

	def reject_organization
	end

	def org_join_request
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")
		@org_id = Organization.find(params[:id])
		@currentUser = current_user.id

		@request = Request.new
		@request.user_id = @currentUser
		@request.org_id = @org_id.id
		@request.status = Request.requests[:pending]
		@request.requested_at = Time.now

		if @request.save
			flash[:success] = "Request has been sent successfully."
			redirect_to dashboard_index_path
		else
			flash[:alert] = "An error occurred. Please try again."
			render :index
		end
	end

	def approve_org_user
		@request = Request.find(params[:id])
		@request.status = Request.requests[:accepted]

		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.organization_id = @request.org_id

		if @request.save and @requestee.save
			flash[:success] = "Approved user"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reject_org_user
		@request = Request.find(params[:id])
		@request.status = Request.requests[:rejected]

		if @request.save
			flash[:alert] = "User rejected"
			redirect_to dashboard_index_path
		end
	end

	def organization_dept_admin
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)

		@assing_candidates = User.all.where(organization_id: @cu_org_id).where(role: "user")
	end

	def dept_join_request
		@organization = Organization.find(params[:o_id])
		@dept_id = Department.find(params[:id])
		@currentUser = current_user.id

		@d_request = DeptRequest.new
		@d_request.user_id = @currentUser
		@d_request.department_id = @dept_id.id
		@d_request.status = DeptRequest.requests[:pending]
		@d_request.requests = Time.now

		if @d_request.save!
			flash[:success] = "Request has been sent successfully."
			redirect_to organization_path(@organization)
		else
			flash[:alert] = "An error occurred. Please try again."
			redirect_to organization_path(@organization)
		end
	end

	def approve_dept_user
		@request = DeptRequest.find(params[:id])
		@request.status = DeptRequest.requests[:accepted]

		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.department_id = @request.department_id
		@requestee.role = User.roles[:student]

		if @request.save and @requestee.save
			flash[:success] = "Approved user"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reject_dept_user
		@request = DeptRequest.find(params[:id])
		@request.status = DeptRequest.requests[:rejected]
		@requestee_id = @request.user_id
		@requestee = User.find(@requestee_id)
		@requestee.role = User.roles[:user]

		if @request.save
			flash[:alert] = "User rejected"
			redirect_to dashboard_index_path
		end
	end

	def organization_editors
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)
		@post_requests = UserPost.all.where(privacy: UserPost.privacies[:private_post])
	end

	def forward_for_review
		@post = UserPost.find(params[:id])
		@post.edit_status = UserPost.edit_statuses[:forwarded]

		if @post.save
			flash[:success] = "Forwarded successfully"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def organization_reviewers
		@currentUser = current_user
		@dept_id = @currentUser.department_id
		@requests = DeptRequest.all.where(department_id: @dept_id).order("requests desc")

		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)
		@organizations = Organization.all.where.not(status: "inactive").where.not(status: "secret")

		@this_dept_admin = @currentUser.role == "dept_admin" ? true : false

		@user_post = UserPost.new
		@all_post = UserPost.all.where(privacy: UserPost.privacies[:public_post]).order(created_at: :desc)
		@review_posts = UserPost.all.where(edit_status: UserPost.edit_statuses[:forwarded])

		@review = Reviewer.new
	end

	def reviewer_accepted
		@post = UserPost.find(params[:id])
		@post.review_status = UserPost.review_statuses[:on_review]

		if @post.save
			flash[:success] = "Accepted"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def reviewer_rejected
		@post = UserPost.find(params[:id])
		@post.review_status = UserPost.review_statuses[:rejected]

		if @post.save
			flash[:success] = "Accepted"
			redirect_to dashboard_index_path
		else
			flash[:error] = "An error occurred. Please try again."
			redirect_to dashboard_index_path
		end
	end

	def organization_students
		@currentUser = User.find(current_user.id)
		@cu_org_id = @currentUser.organization_id
		@cu_dept_id = @currentUser.department_id
		@cu_dept_members = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:student])
		@cu_dept_editors = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_editor])
		@cu_dept_reviewers = User.all.where(department_id: @cu_dept_id).where(role: User.roles[:dept_reviewer])
		@cu_organization = Organization.find(@cu_org_id)
		@cu_department = Department.find(@cu_dept_id)

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/partials/_dashboard.html.erb
<div class="row shared-dashboard">
	<div class="col-sm-2 left-box">
		<div class="top text-center">
			<ul>
				<!--
				<li><img src="<%=@cu_organization.image.present? ? @cu_organization.image : ""%>" alt="<%=@cu_organization.name%>"></li>
				<li><img src="<%=@cu_department.image.present? ? @cu_department.image : ""%>" alt="<%=@cu_department.name%>"></li>
				-->
				<li><img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png"></li>
				<li><img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png"></li>
			</ul>
			<br>
			<h6> <strong><%=@cu_organization.name%></strong> </h6>
			<h4> <strong><%=@cu_department.name%></strong> </h4>
			<hr>
		</div><!--top-->
		<div class="middle">
			<ul>
				<li class="name"><h6>User: <strong><%=@currentUser.email%></h6></strong></li>
				<li class="role"><h6>Status: <%=@currentUser.role.humanize%></h6></li>
				<li> <a href=""><h6>Profile</h6></a> </li>
				<li> <a href=""><h6>Settings</h6></a> </li>
			</ul>
			<hr>
		</div><!--middle-->
		<div class="bottom">
			<h6>Members</h6>
			<ul class="members">
				<%@cu_dept_members.each do |dept_user|%>
					<!--<li> <a href=""> <%= image_tag 'user.png', :title => dept_user.email%> </a> </li>-->
					<li> <img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=dept_user.email%>"> </li>
				<%end%>
			</ul>
			<h6>Editors</h6>
			<ul class="members">
				<%@cu_dept_editors.each do |dept_editor|%>
					<!--<li> <a href=""> <%= image_tag 'editor.jpg', :title => dept_editor.email%> </a> </li>-->
					<li> <img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=dept_editor.email%>"> </li>
				<%end%>
			</ul>
			<h6>Reviewers</h6>
			<ul class="members">
				<%@cu_dept_reviewers.each do |dept_reviewer|%>
					<!--<li> <a href=""> <%= image_tag 'reviewer.jpg', :title => dept_reviewer.email%> </a> </li>-->
					<li> <img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=dept_reviewer.email%>"> </li>
				<%end%>
			</ul>
		</div><!--bottom-->
	</div><!--left-box-->
	<div class="col-sm-8 center-box">
		<div class="row">
			<%= bootstrap_form_for @user_post, url: user_posts_path, multipart: true, remote: true, layout: :vertical do |f| %>
				<%if f.object.errors.any?%>
					<div class="alert alert-danger alert-dismissible" style="margin-top:5px;" role="alert">
			  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  		<strong>Please fix the following fields:</strong>
			  		<ul>
				        <%f.object.errors.full_messages.each do |message| %>
				            <li><%= message %></li>
				        <% end %>
			        </ul> 
				</div>
				<%end%>

				<div class="text-center" id="post-now">
					<div class="col-sm-12">
						<ul>
							<li>
								<%= f.text_area :post_content, :placeholder => "Write something here", :rows => '3', :cols => '100'%>
							</li>
							<li>
								<%= f.select :post_type, UserPost.post_types.keys.map { |w| [w.humanize, w] },{},{ :class => 'my_style_class' }%>
								<%= f.select :privacy, UserPost.privacies.keys.map { |w| [w.humanize, w] }%>
								<%= f.select :post_genre, UserPost.genres.keys.map { |w| [w.humanize, w] }%>
							</li>
							<li id="file-upload" class="">
								<%= f.file_field :document %>
							</li>
							<li> <a id="show-upload" class="btn btn-success">Upload</a>&nbsp;&nbsp;<%= f.submit "Post now", :class => 'btn btn-primary'%></li>
						</ul>
					</div>
				</div><!--post-now-->
			<% end %>
		</div>

		<hr>

		<% @all_post.each do |post|%>
		<div class="row">
			<div class="col-sm-12 post-wrapper">
				<div class="col-sm-2 user-img text-center">
					<div class="user-img-wrapper">
						<a href=""> 
							<!--<%= image_tag 'user.png', :title => ""%> -->
							<img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=User.find(post.user_id).email%>">
						</a>
						<p><strong><%= User.find(post.user_id).email%></strong></p>
					</div>
				</div>
				<div class="col-sm-10 user-post">
					<div class="options pull-right">
						<div class="dropdown">
						  <div href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
						  <ul class="dropdown-menu" aria-labelledby="dLabel">
						  	<%if post.user_id == @currentUser.id %>
						    <li><a href="">Edit</a></li>
						    <%end%>
						    <%if post.user_id == @currentUser.id or @this_dept_admin %>
						    <li>
						    	<%= link_to "Delete",  user_post_path(post), method: :delete, :class => "color-red", data: { confirm: 'Are you sure?' } %>
						    </li>
						    <%end%>
						    <%if @this_dept_admin %>
						    <li><a href="">Block user</a></li>
						    <%end%>
						  </ul>
						</div>
					</div>
					<div class="info">
						<span class="pull-left"> <i><%= User.find(post.user_id).email%> 
							<%if post.post_type == "file"%>
								Uploaded a document
							<%elsif post.post_type == "post"%>
								Posted a post
							<%elsif post.post_type == "both"%>
								Posted a post and Uploaded a document
							<%end%>
						</i> </span>
						<span class="pull-right"> <strong><%= post.created_at %></strong> </span>
					</div><br>
					<div class="content">
						<%= post.post_content%>
					</div><br>
					<div class="attachment">
						<%if post.document.exists?%>
						<i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;attachment included <a href="<%=post.document.url%>"><%=post.document_file_name[0..50]%></a>
						<%end%>
					</div>
				</div>
			</div>
		</div>
		<hr>
		<%end%>

	</div><!--center-box-->
	<div class="col-sm-2 right-box">
		<a class="btn btn-block btn-default">Compose</a>
		<a class="btn btn-block btn-primary">Inbox</a>

		<hr>

		<div class="chatbox">
			<div class="header text-center"><h4>CHATBOX</h4></div>
			<div class="contents"></div>
		</div>

		<div class="guides">
			<ul>
				<li><a href="">Terms and conditions</a></li>
				<li><a href="">Help and support</a></li>
				<li><a href="">Allowed parameters</a></li>
			</ul>
		</div>
	</div><!--right-box-->
</div>

app/views/dashboard/partials/_organization.html.erb
<br>
<div class="row">

	<div class="col-sm-6 dept-box">
		<h3><strong>MY ORGANIZATION</strong></h3>
		<div class="dept-box-wrapper">
			<div class="row dept-row">
				<div class="col-sm-6 dept-icon"> 
					<!--
					<%if @cu_organization.image.present?%>
						<%= image_tag "#{@cu_organization.image}" %>
					<%end%>
					-->
					<img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=@cu_organization.name%>">
				</div>
				<div class="col-sm-6"> <%= @cu_organization.name%> </div>
			</div>
		</div>
	</div>

	<div class="col-sm-6 dept-box">
		<h3><strong>MY DEPARTMENT</strong></h3>
		<div class="dept-box-wrapper">
			<div class="row dept-row">
				<div class="col-sm-6 dept-icon"> 
					<!--
					<%if @cu_department.image.present?%>
						<%= image_tag "#{@cu_department.image}" %>
					<%end%>
					-->
					<img src="http://www.hsdtaxlaw.com/wp-content/uploads/2016/05/20140806_LogoSupporterPlaceholder.png" title="<%=@cu_department.name%>">
				</div>
				<div class="col-sm-6"> <%=@cu_department.name%> </div>
			</div>
		</div>
	</div>

</div>

app/views/dashboard/partials/_organization_all.html.erb
<br>
<div class="row">
	<div class="col-sm-12">

		<% @organizations.each do |organization| %>
		<div class="col-sm-3 org-box">
			<div class="org-box-wrapper">
				<div class="title"><a href=""><%= organization.name %></a></div>
				<div class="info">
					<ul>
						<li class="members"><%= User.all.where(organization_id: organization.id).count > 0 ? User.all.where(organization_id: organization.id).count : 0 %> members</li>
						<li></li>
						<% if @currentUser.requests.where(org_id: organization.id).where(status: 0).exists? %>
							<li>
								<button class="btn btn-warning">Pending</button>
							</li>
						<% elsif @currentUser.requests.where(org_id: organization.id).where(status: 1).exists? %>
							<li>
								<button class="btn btn-success">Member</button>
							</li>
						<% else %>
							<li>
								<%= link_to "Request to join", org_join_request_dashboard_index_path(:id => organization.id), :class => "btn btn-info" %>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>