config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	devise_scope :user do
		authenticated :user do
			root 'dashboard#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end

	resources :users
	resources :dashboard do
		get 'super_admin',							on: :collection
		get 'organization_super_admin',				on: :collection
		get 'organization_dept_admin',				on: :collection
		get 'organization_editors',					on: :collection
		get 'organization_reviewers',				on: :collection
		get 'organization_students',				on: :collection
		get 'activate_organization',				on: :collection
		get 'reject_organization',					on: :collection
		get 'org_join_request',						on: :collection
		get 'approve_org_user',						on: :collection
		get 'reject_org_user',						on: :collection
		get 'dept_join_request',					on: :collection
		get 'approve_dept_user',					on: :collection
		get 'reject_dept_user',						on: :collection
		get 'forward_for_review',					on: :collection
		get 'reviewer_accepted',					on: :collection
		get 'reviewer_rejected',					on: :collection

	end
	resources :organizations
	resources :departments do
		get 'change_admin',							on: :collection
		patch 'update_admin',						on: :collection
	end

  	resources :user_posts do
  	end

  	resources :editor
	resources :reviewer

	if Rails.env.development?
		mount LetterOpenerWeb::Engine, at: "/letter_opener"
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_one :posts
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	has_many :dept_requests
end

app/models/dept_request.rb
class DeptRequest < ApplicationRecord

	enum request: [:pending, :accepted, :rejected]
	after_initialize :set_default_request, :if => :new_record?

	def set_default_request
		self.status ||= :pending
	end

	validates_uniqueness_of :user_id, scope: [:department_id]

	belongs_to :user
	belongs_to :department, optional: true
end

app/models/editor.rb
class Editor < ApplicationRecord
	has_many :posts
end

app/models/organization.rb
class Organization < ApplicationRecord
	enum status: [:open, :secret, :closed, :inactive]
	after_initialize :set_default_status, :if => :new_record?

	def set_default_status
		self.status ||= :inactive
	end

	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :requests,    class_name: "Request", foreign_key: "org_id"
	has_many :users
end

app/models/request.rb
class Request < ApplicationRecord

	enum request: [:pending, :accepted, :rejected]
	after_initialize :set_default_request, :if => :new_record?

	def set_default_request
		self.status ||= :pending
	end

	validates_uniqueness_of :user_id, scope: [:org_id]

	belongs_to :user
	belongs_to :organization,    class_name: "Organization", foreign_key: "org_id", optional: true
end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
	belongs_to :user_post,    class_name: "UserPost", foreign_key: "id", optional: true
end

app/models/user.rb
class User < ApplicationRecord

	enum role: [:superadmin, :user, :org_super_admin, :dept_admin, :dept_editor, :dept_reviewer, :student]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	has_many :requests
	has_many :dept_requests
	has_many :user_posts

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable
end

app/models/user_post.rb
class UserPost < ApplicationRecord

	has_attached_file :document, :path => ":rails_root/public/system/:attachment/:id/:style/:filename"

	allowed_content_type = [
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/jpg',
    'image/gif'
    ]
	validates_attachment_content_type :document, :content_type => allowed_content_type, :message=> "Only #{allowed_content_type} is allowed"

	enum post_type: [:file, :post, :both]
	enum privacy: [:public_post, :private_post]
	enum genre: [:post_only, :article, :paper, :concept]
	enum edit_status: [:pending, :forwarded, :accepted]
	enum review_status: [:no_reviewer, :on_review, :rejected, :complete]

	after_initialize :set_default_privacy, :if => :new_record?
	after_initialize :set_default_edit_status, :if => :new_record?
	after_initialize :set_default_review_status, :if => :new_record?

	def set_default_privacy
		self.privacy ||= :private_post
	end

	def set_default_edit_status
		self.edit_status ||= :pending
	end

	def set_default_review_status
		self.review_status ||= :no_reviewer
	end

	has_many :comments
	has_one :users
	has_one :editors
	has_many :reviewers,    class_name: "Reviewer", foreign_key: "post_id"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_user!, :only => [:index]

	def index
	end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

	before_action :org_super_admin_only!, only: [:edit, :update, :destroy]

	def new
		@organization = Organization.new
	end

	def create
		@currentUser = current_user.id
		@organization = Organization.new(organization_params)
		@organization.super_admin = @currentUser
		
		if @organization.save
			redirect_to dashboard_index_path,success: "Request successfull! A reviewer will review and notify you soon."
		else
			render :new
		end
	end

	def show
		@organization = Organization.find(params[:id])
		@currentUser = current_user;
		@departments = Department.all.where(organization_id: @organization.id)
	end

	def edit
		@organization = Organization.find(params[:id])
	end

	def update
		@organization = Organization.find(params[:id])
	end

	def destroy
		@organization = Organization.find(params[:id])
	end


	private

	def organization_params
	  	params.require(:organization).permit(:id,:name, :email)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	after_action :verify_authorized

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])

		if user.update_attributes(secure_params)
			redirect_to users_path, :notice => "User updated."
	    else
	      redirect_to users_path, :alert => "Unable to update user."
	    end
	end

	def destroy
		user = User.find(params[:id])

		user.destroy
		redirect_to users_path, :notice => "User deleted"
	end

	private

	def secure_params
		params.require(:user).permit(:id, :role, :department_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/reviewer_helper.rb
module ReviewerHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/organizations/new.html.erb
<div class="page-title">
    <h3>CREATE A NEW ORGANIZATION</h3>
</div>

<%= bootstrap_form_for @organization, url: organizations_path, multipart: true, remote: true, layout: :vertical do |f| %>

	<%if f.object.errors.any?%>
		<div class="alert alert-danger alert-dismissible" style="margin-top:5px;" role="alert">
  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  		<strong>Please fix the following fields:</strong>
  		<ul>
	        <%f.object.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
	        <% end %>
        </ul> 
	</div>
	<%end%>
	
	<div class= "row">
		<div class="col-sm-4">
			<%= f.text_field :name, label: "Organization Name"%>
			<%= f.text_field :email%>
		</div>
	</div>
	
	

	<%= f.submit "CREATE ORGANIZATION", :class => 'btn btn-primary'%>
	<br>
<%end%>

app/views/organizations/show.html.erb
<section id="dashboard-home">
	<div class="row">
		<div class="col-sm-12 text-center"> <h4><strong><%= @organization.name%></strong></h4> </div>
	</div>
	<hr>
	<div class="row user-dashboard-departments">
		<div class="col-sm-12">

			<% @departments.each do |department| %>
			<div class="col-sm-3 org-box">
				<div class="org-box-wrapper">
					<div class="image"> <img src="<%= department.image.present? ? department.image : '' %>" alt="<%= department.name %>"> </div>
					<div class="info">
						<ul>
							<% if User.find(@currentUser.id).dept_requests.where(department_id: department.id).where(status: 0).exists? %>
								<li>
									<button class="btn btn-warning">Pending</button>
								</li>
							<% elsif User.find(@currentUser.id).dept_requests.where(department_id: department.id).where(status: 1).exists? %>
								<li><%= link_to "Enter", department_path(department.id), :class=>"btn btn-primary" %></li>
								<li>
									<button class="btn btn-success">Member</button>
								</li>
							<% else %>
								<li>
									<%= link_to "Request to join", dept_join_request_dashboard_index_path(:id => department.id, :o_id => @organization.id), :class => "btn btn-info" %>
								</li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</section><!--#dashboard-home-->